// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: terminal_agent/v1/device.proto

#include "terminal_agent/v1/device.pb.h"
#include "terminal_agent/v1/device.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace terminal_agent {
namespace v1 {

}  // namespace terminal_agent
}  // namespace v1

