// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: terminal_agent/v1/service.proto
// Protobuf C++ Version: 7.34.1

#include "terminal_agent/v1/service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace terminal_agent {
namespace v1 {

inline constexpr CommandResultResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        accepted_{false} {}

template <typename>
constexpr CommandResultResponse::CommandResultResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CommandResultResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct CommandResultResponseDefaultTypeInternal {
  constexpr CommandResultResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandResultResponseDefaultTypeInternal() {}
  union {
    CommandResultResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandResultResponseDefaultTypeInternal _CommandResultResponse_default_instance_;
}  // namespace v1
}  // namespace terminal_agent
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_terminal_5fagent_2fv1_2fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_terminal_5fagent_2fv1_2fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_terminal_5fagent_2fv1_2fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::terminal_agent::v1::CommandResultResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::terminal_agent::v1::CommandResultResponse, _impl_.accepted_),
        PROTOBUF_FIELD_OFFSET(::terminal_agent::v1::CommandResultResponse, _impl_.message_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::terminal_agent::v1::CommandResultResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::terminal_agent::v1::_CommandResultResponse_default_instance_._instance,
};
const char descriptor_table_protodef_terminal_5fagent_2fv1_2fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\037terminal_agent/v1/service.proto\022\021termi"
    "nal_agent.v1\032\036terminal_agent/v1/device.p"
    "roto\":\n\025CommandResultResponse\022\020\n\010accepte"
    "d\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\373\002\n\rDeviceServi"
    "ce\022V\n\tHeartbeat\022#.terminal_agent.v1.Hear"
    "tbeatRequest\032$.terminal_agent.v1.Heartbe"
    "atResponse\022X\n\014ReportStatus\022\037.terminal_ag"
    "ent.v1.StatusReport\032\'.terminal_agent.v1."
    "StatusReportResponse\022U\n\013ReportEvent\022\036.te"
    "rminal_agent.v1.EventReport\032&.terminal_a"
    "gent.v1.EventReportResponse\022a\n\023ReportCom"
    "mandResult\022 .terminal_agent.v1.CommandRe"
    "sult\032(.terminal_agent.v1.CommandResultRe"
    "sponse2h\n\016CommandService\022V\n\rCommandStrea"
    "m\022\'.terminal_agent.v1.CommandStreamReque"
    "st\032\032.terminal_agent.v1.Command0\001B;Z9gith"
    "ub.com/QF1987/terminal-agent-go/gen/term"
    "inal_agent/v1b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_deps[1] = {
        &::descriptor_table_terminal_5fagent_2fv1_2fdevice_2eproto,
};
static ::absl::once_flag descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto = {
    false,
    false,
    701,
    descriptor_table_protodef_terminal_5fagent_2fv1_2fservice_2eproto,
    "terminal_agent/v1/service.proto",
    &descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_once,
    descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_terminal_5fagent_2fv1_2fservice_2eproto::offsets,
    file_level_enum_descriptors_terminal_5fagent_2fv1_2fservice_2eproto,
    file_level_service_descriptors_terminal_5fagent_2fv1_2fservice_2eproto,
};
namespace terminal_agent {
namespace v1 {
// ===================================================================

class CommandResultResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CommandResultResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_._has_bits_);
};

CommandResultResponse::CommandResultResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CommandResultResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:terminal_agent.v1.CommandResultResponse)
}
PROTOBUF_NDEBUG_INLINE CommandResultResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::terminal_agent::v1::CommandResultResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_(arena, from.message_) {}

CommandResultResponse::CommandResultResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CommandResultResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CommandResultResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CommandResultResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.accepted_ = from._impl_.accepted_;

  // @@protoc_insertion_point(copy_constructor:terminal_agent.v1.CommandResultResponse)
}
PROTOBUF_NDEBUG_INLINE CommandResultResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        message_(arena) {}

inline void CommandResultResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.accepted_ = {};
}
CommandResultResponse::~CommandResultResponse() {
  // @@protoc_insertion_point(destructor:terminal_agent.v1.CommandResultResponse)
  SharedDtor(*this);
}
inline void CommandResultResponse::SharedDtor(MessageLite& self) {
  CommandResultResponse& this_ = static_cast<CommandResultResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CommandResultResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CommandResultResponse(arena);
}
constexpr auto CommandResultResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CommandResultResponse),
                                            alignof(CommandResultResponse));
}
constexpr auto CommandResultResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CommandResultResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &CommandResultResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CommandResultResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CommandResultResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CommandResultResponse>(), &CommandResultResponse::ByteSizeLong,
              &CommandResultResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_._cached_size_),
          false,
      },
      &CommandResultResponse::kDescriptorMethods,
      &descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CommandResultResponse_class_data_ =
        CommandResultResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CommandResultResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CommandResultResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CommandResultResponse_class_data_.tc_table);
  return CommandResultResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 55, 2>
CommandResultResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CommandResultResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::terminal_agent::v1::CommandResultResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_.message_)}},
    // bool accepted = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CommandResultResponse, _impl_.accepted_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_.accepted_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool accepted = 1;
    {PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_.accepted_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_.message_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\47\0\7\0\0\0\0\0"
    "terminal_agent.v1.CommandResultResponse"
    "message"
  }},
};
PROTOBUF_NOINLINE void CommandResultResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:terminal_agent.v1.CommandResultResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  _impl_.accepted_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CommandResultResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CommandResultResponse& this_ = static_cast<const CommandResultResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CommandResultResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CommandResultResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:terminal_agent.v1.CommandResultResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool accepted = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_accepted() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_accepted(), target);
    }
  }

  // string message = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_message().empty()) {
      const ::std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "terminal_agent.v1.CommandResultResponse.message");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:terminal_agent.v1.CommandResultResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CommandResultResponse::ByteSizeLong(const MessageLite& base) {
  const CommandResultResponse& this_ = static_cast<const CommandResultResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CommandResultResponse::ByteSizeLong() const {
  const CommandResultResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:terminal_agent.v1.CommandResultResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string message = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message());
      }
    }
    // bool accepted = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_accepted() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CommandResultResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CommandResultResponse*>(&to_msg);
  auto& from = static_cast<const CommandResultResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:terminal_agent.v1.CommandResultResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_message().empty()) {
        _this->_internal_set_message(from._internal_message());
      } else {
        if (_this->_impl_.message_.IsDefault()) {
          _this->_internal_set_message("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_accepted() != 0) {
        _this->_impl_.accepted_ = from._impl_.accepted_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CommandResultResponse::CopyFrom(const CommandResultResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:terminal_agent.v1.CommandResultResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CommandResultResponse::InternalSwap(CommandResultResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.accepted_, other->_impl_.accepted_);
}

::google::protobuf::Metadata CommandResultResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace terminal_agent
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
