// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: terminal_agent/v1/service.proto

#include "terminal_agent/v1/service.pb.h"
#include "terminal_agent/v1/service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace terminal_agent {
namespace v1 {

static const char* DeviceService_method_names[] = {
  "/terminal_agent.v1.DeviceService/Heartbeat",
  "/terminal_agent.v1.DeviceService/ReportStatus",
  "/terminal_agent.v1.DeviceService/ReportEvent",
  "/terminal_agent.v1.DeviceService/ReportCommandResult",
};

std::unique_ptr< DeviceService::Stub> DeviceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DeviceService::Stub> stub(new DeviceService::Stub(channel, options));
  return stub;
}

DeviceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Heartbeat_(DeviceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReportStatus_(DeviceService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReportEvent_(DeviceService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReportCommandResult_(DeviceService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DeviceService::Stub::Heartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::terminal_agent::v1::HeartbeatResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::terminal_agent::v1::HeartbeatRequest, ::terminal_agent::v1::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Heartbeat_, context, request, response);
}

void DeviceService::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest* request, ::terminal_agent::v1::HeartbeatResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::terminal_agent::v1::HeartbeatRequest, ::terminal_agent::v1::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest* request, ::terminal_agent::v1::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::HeartbeatResponse>* DeviceService::Stub::PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::terminal_agent::v1::HeartbeatResponse, ::terminal_agent::v1::HeartbeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Heartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::HeartbeatResponse>* DeviceService::Stub::AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHeartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceService::Stub::ReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::terminal_agent::v1::StatusReportResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::terminal_agent::v1::StatusReport, ::terminal_agent::v1::StatusReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportStatus_, context, request, response);
}

void DeviceService::Stub::async::ReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport* request, ::terminal_agent::v1::StatusReportResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::terminal_agent::v1::StatusReport, ::terminal_agent::v1::StatusReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportStatus_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::ReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport* request, ::terminal_agent::v1::StatusReportResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::StatusReportResponse>* DeviceService::Stub::PrepareAsyncReportStatusRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::terminal_agent::v1::StatusReportResponse, ::terminal_agent::v1::StatusReport, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::StatusReportResponse>* DeviceService::Stub::AsyncReportStatusRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceService::Stub::ReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::terminal_agent::v1::EventReportResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::terminal_agent::v1::EventReport, ::terminal_agent::v1::EventReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportEvent_, context, request, response);
}

void DeviceService::Stub::async::ReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport* request, ::terminal_agent::v1::EventReportResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::terminal_agent::v1::EventReport, ::terminal_agent::v1::EventReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportEvent_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::ReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport* request, ::terminal_agent::v1::EventReportResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportEvent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::EventReportResponse>* DeviceService::Stub::PrepareAsyncReportEventRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::terminal_agent::v1::EventReportResponse, ::terminal_agent::v1::EventReport, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportEvent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::EventReportResponse>* DeviceService::Stub::AsyncReportEventRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportEventRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceService::Stub::ReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::terminal_agent::v1::CommandResultResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::terminal_agent::v1::CommandResult, ::terminal_agent::v1::CommandResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportCommandResult_, context, request, response);
}

void DeviceService::Stub::async::ReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult* request, ::terminal_agent::v1::CommandResultResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::terminal_agent::v1::CommandResult, ::terminal_agent::v1::CommandResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportCommandResult_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::ReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult* request, ::terminal_agent::v1::CommandResultResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportCommandResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::CommandResultResponse>* DeviceService::Stub::PrepareAsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::terminal_agent::v1::CommandResultResponse, ::terminal_agent::v1::CommandResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportCommandResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::CommandResultResponse>* DeviceService::Stub::AsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportCommandResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

DeviceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::terminal_agent::v1::HeartbeatRequest, ::terminal_agent::v1::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::terminal_agent::v1::HeartbeatRequest* req,
             ::terminal_agent::v1::HeartbeatResponse* resp) {
               return service->Heartbeat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::terminal_agent::v1::StatusReport, ::terminal_agent::v1::StatusReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::terminal_agent::v1::StatusReport* req,
             ::terminal_agent::v1::StatusReportResponse* resp) {
               return service->ReportStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::terminal_agent::v1::EventReport, ::terminal_agent::v1::EventReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::terminal_agent::v1::EventReport* req,
             ::terminal_agent::v1::EventReportResponse* resp) {
               return service->ReportEvent(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::terminal_agent::v1::CommandResult, ::terminal_agent::v1::CommandResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::terminal_agent::v1::CommandResult* req,
             ::terminal_agent::v1::CommandResultResponse* resp) {
               return service->ReportCommandResult(ctx, req, resp);
             }, this)));
}

DeviceService::Service::~Service() {
}

::grpc::Status DeviceService::Service::Heartbeat(::grpc::ServerContext* context, const ::terminal_agent::v1::HeartbeatRequest* request, ::terminal_agent::v1::HeartbeatResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceService::Service::ReportStatus(::grpc::ServerContext* context, const ::terminal_agent::v1::StatusReport* request, ::terminal_agent::v1::StatusReportResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceService::Service::ReportEvent(::grpc::ServerContext* context, const ::terminal_agent::v1::EventReport* request, ::terminal_agent::v1::EventReportResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceService::Service::ReportCommandResult(::grpc::ServerContext* context, const ::terminal_agent::v1::CommandResult* request, ::terminal_agent::v1::CommandResultResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* CommandService_method_names[] = {
  "/terminal_agent.v1.CommandService/CommandStream",
};

std::unique_ptr< CommandService::Stub> CommandService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CommandService::Stub> stub(new CommandService::Stub(channel, options));
  return stub;
}

CommandService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CommandStream_(CommandService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::terminal_agent::v1::Command>* CommandService::Stub::CommandStreamRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::terminal_agent::v1::Command>::Create(channel_.get(), rpcmethod_CommandStream_, context, request);
}

void CommandService::Stub::async::CommandStream(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest* request, ::grpc::ClientReadReactor< ::terminal_agent::v1::Command>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::terminal_agent::v1::Command>::Create(stub_->channel_.get(), stub_->rpcmethod_CommandStream_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::terminal_agent::v1::Command>* CommandService::Stub::AsyncCommandStreamRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::terminal_agent::v1::Command>::Create(channel_.get(), cq, rpcmethod_CommandStream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::terminal_agent::v1::Command>* CommandService::Stub::PrepareAsyncCommandStreamRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::terminal_agent::v1::Command>::Create(channel_.get(), cq, rpcmethod_CommandStream_, context, request, false, nullptr);
}

CommandService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CommandService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< CommandService::Service, ::terminal_agent::v1::CommandStreamRequest, ::terminal_agent::v1::Command>(
          [](CommandService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::terminal_agent::v1::CommandStreamRequest* req,
             ::grpc::ServerWriter<::terminal_agent::v1::Command>* writer) {
               return service->CommandStream(ctx, req, writer);
             }, this)));
}

CommandService::Service::~Service() {
}

::grpc::Status CommandService::Service::CommandStream(::grpc::ServerContext* context, const ::terminal_agent::v1::CommandStreamRequest* request, ::grpc::ServerWriter< ::terminal_agent::v1::Command>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace terminal_agent
}  // namespace v1

