// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: terminal_agent/v1/service.proto

#include "terminal_agent/v1/service.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace terminal_agent {
namespace v1 {

inline constexpr CommandResultResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        accepted_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CommandResultResponse::CommandResultResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CommandResultResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandResultResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandResultResponseDefaultTypeInternal() {}
  union {
    CommandResultResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandResultResponseDefaultTypeInternal _CommandResultResponse_default_instance_;
}  // namespace v1
}  // namespace terminal_agent
static ::_pb::Metadata file_level_metadata_terminal_5fagent_2fv1_2fservice_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_terminal_5fagent_2fv1_2fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_terminal_5fagent_2fv1_2fservice_2eproto = nullptr;
const ::uint32_t TableStruct_terminal_5fagent_2fv1_2fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::terminal_agent::v1::CommandResultResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::terminal_agent::v1::CommandResultResponse, _impl_.accepted_),
    PROTOBUF_FIELD_OFFSET(::terminal_agent::v1::CommandResultResponse, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::terminal_agent::v1::CommandResultResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::terminal_agent::v1::_CommandResultResponse_default_instance_._instance,
};
const char descriptor_table_protodef_terminal_5fagent_2fv1_2fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\037terminal_agent/v1/service.proto\022\021termi"
    "nal_agent.v1\032\036terminal_agent/v1/device.p"
    "roto\":\n\025CommandResultResponse\022\020\n\010accepte"
    "d\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\373\002\n\rDeviceServi"
    "ce\022V\n\tHeartbeat\022#.terminal_agent.v1.Hear"
    "tbeatRequest\032$.terminal_agent.v1.Heartbe"
    "atResponse\022X\n\014ReportStatus\022\037.terminal_ag"
    "ent.v1.StatusReport\032\'.terminal_agent.v1."
    "StatusReportResponse\022U\n\013ReportEvent\022\036.te"
    "rminal_agent.v1.EventReport\032&.terminal_a"
    "gent.v1.EventReportResponse\022a\n\023ReportCom"
    "mandResult\022 .terminal_agent.v1.CommandRe"
    "sult\032(.terminal_agent.v1.CommandResultRe"
    "sponse2h\n\016CommandService\022V\n\rCommandStrea"
    "m\022\'.terminal_agent.v1.CommandStreamReque"
    "st\032\032.terminal_agent.v1.Command0\001B;Z9gith"
    "ub.com/QF1987/terminal-agent-go/gen/term"
    "inal_agent/v1b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_deps[1] =
    {
        &::descriptor_table_terminal_5fagent_2fv1_2fdevice_2eproto,
};
static ::absl::once_flag descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto = {
    false,
    false,
    701,
    descriptor_table_protodef_terminal_5fagent_2fv1_2fservice_2eproto,
    "terminal_agent/v1/service.proto",
    &descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_once,
    descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_terminal_5fagent_2fv1_2fservice_2eproto::offsets,
    file_level_metadata_terminal_5fagent_2fv1_2fservice_2eproto,
    file_level_enum_descriptors_terminal_5fagent_2fv1_2fservice_2eproto,
    file_level_service_descriptors_terminal_5fagent_2fv1_2fservice_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_getter() {
  return &descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_terminal_5fagent_2fv1_2fservice_2eproto(&descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto);
namespace terminal_agent {
namespace v1 {
// ===================================================================

class CommandResultResponse::_Internal {
 public:
};

CommandResultResponse::CommandResultResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:terminal_agent.v1.CommandResultResponse)
}
inline PROTOBUF_NDEBUG_INLINE CommandResultResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

CommandResultResponse::CommandResultResponse(
    ::google::protobuf::Arena* arena,
    const CommandResultResponse& from)
    : ::google::protobuf::Message(arena) {
  CommandResultResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.accepted_ = from._impl_.accepted_;

  // @@protoc_insertion_point(copy_constructor:terminal_agent.v1.CommandResultResponse)
}
inline PROTOBUF_NDEBUG_INLINE CommandResultResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void CommandResultResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.accepted_ = {};
}
CommandResultResponse::~CommandResultResponse() {
  // @@protoc_insertion_point(destructor:terminal_agent.v1.CommandResultResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CommandResultResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CommandResultResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:terminal_agent.v1.CommandResultResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.accepted_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CommandResultResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 55, 2> CommandResultResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CommandResultResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_.message_)}},
    // bool accepted = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CommandResultResponse, _impl_.accepted_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_.accepted_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool accepted = 1;
    {PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_.accepted_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(CommandResultResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\47\0\7\0\0\0\0\0"
    "terminal_agent.v1.CommandResultResponse"
    "message"
  }},
};

::uint8_t* CommandResultResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:terminal_agent.v1.CommandResultResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool accepted = 1;
  if (this->_internal_accepted() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_accepted(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "terminal_agent.v1.CommandResultResponse.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:terminal_agent.v1.CommandResultResponse)
  return target;
}

::size_t CommandResultResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:terminal_agent.v1.CommandResultResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // bool accepted = 1;
  if (this->_internal_accepted() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CommandResultResponse::_class_data_ = {
    CommandResultResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CommandResultResponse::GetClassData() const {
  return &_class_data_;
}

void CommandResultResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CommandResultResponse*>(&to_msg);
  auto& from = static_cast<const CommandResultResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:terminal_agent.v1.CommandResultResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_accepted() != 0) {
    _this->_internal_set_accepted(from._internal_accepted());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CommandResultResponse::CopyFrom(const CommandResultResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:terminal_agent.v1.CommandResultResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CommandResultResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CommandResultResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CommandResultResponse::InternalSwap(CommandResultResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.accepted_, other->_impl_.accepted_);
}

::google::protobuf::Metadata CommandResultResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_getter, &descriptor_table_terminal_5fagent_2fv1_2fservice_2eproto_once,
      file_level_metadata_terminal_5fagent_2fv1_2fservice_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace terminal_agent
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
