// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: terminal_agent/v1/service.proto
#ifndef GRPC_terminal_5fagent_2fv1_2fservice_2eproto__INCLUDED
#define GRPC_terminal_5fagent_2fv1_2fservice_2eproto__INCLUDED

#include "terminal_agent/v1/service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace terminal_agent {
namespace v1 {

// ============================================================
// terminal-agent gRPC 服务定义
//
// 包含两个 service：
//   1. DeviceService — 设备端调用（心跳、上报、回报）
//   2. CommandService — 服务端推送指令给设备
//
// 所有 RPC 的认证通过 metadata 传递 AuthContext 实现
// ============================================================
//
// ─── DeviceService ───────────────────────────────────────
// 设备端调用的服务，包含所有"设备 → 服务端"的 RPC
//
// 设备端只需要连接这一个 service 即可完成所有操作
class DeviceService final {
 public:
  static constexpr char const* service_full_name() {
    return "terminal_agent.v1.DeviceService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 心跳
    // 设备定期（建议 30-60 秒）调用，告知服务端"我还活着"
    // 服务端更新 last_heartbeat，并通过响应告知是否有待执行指令
    //
    // 调用频率：每 30-60 秒一次
    // 超时建议：5 秒
    // 失败处理：连续失败 3 次，设备应记录本地日志并尝试重新注册
    virtual ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::terminal_agent::v1::HeartbeatResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::HeartbeatResponse>> AsyncHeartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::HeartbeatResponse>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::HeartbeatResponse>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::HeartbeatResponse>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    // 状态上报
    // 设备上报完整运行状态快照，包含性能指标和当前配置
    //
    // 调用频率：每 5 分钟一次，或状态发生重大变化时立即调用
    // 重大变化：status 变更、配置修改、固件升级完成、重启完成
    // 超时建议：10 秒
    // 失败处理：记录本地日志，下次周期重试（不需要立即重试，数据有周期性补偿）
    virtual ::grpc::Status ReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::terminal_agent::v1::StatusReportResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::StatusReportResponse>> AsyncReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::StatusReportResponse>>(AsyncReportStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::StatusReportResponse>> PrepareAsyncReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::StatusReportResponse>>(PrepareAsyncReportStatusRaw(context, request, cq));
    }
    // 事件上报
    // 设备端发生特定事件时实时上报（故障、交易失败、配置变更、重启等）
    //
    // 调用频率：事件驱动，不固定
    // 超时建议：10 秒
    // 失败处理：写入本地持久化队列，网络恢复后重试（事件数据不能丢）
    virtual ::grpc::Status ReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::terminal_agent::v1::EventReportResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::EventReportResponse>> AsyncReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::EventReportResponse>>(AsyncReportEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::EventReportResponse>> PrepareAsyncReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::EventReportResponse>>(PrepareAsyncReportEventRaw(context, request, cq));
    }
    // 指令执行结果回报
    // 设备执行完服务端下发的指令后，通过此 RPC 回报执行结果
    //
    // 调用频率：指令执行完后调用
    // 超时建议：10 秒
    // 失败处理：写入本地持久化队列，网络恢复后重试
    // 注意：command_id 必须与收到的 Command.command_id 一致
    virtual ::grpc::Status ReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::terminal_agent::v1::CommandResultResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::CommandResultResponse>> AsyncReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::CommandResultResponse>>(AsyncReportCommandResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::CommandResultResponse>> PrepareAsyncReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::CommandResultResponse>>(PrepareAsyncReportCommandResultRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 心跳
      // 设备定期（建议 30-60 秒）调用，告知服务端"我还活着"
      // 服务端更新 last_heartbeat，并通过响应告知是否有待执行指令
      //
      // 调用频率：每 30-60 秒一次
      // 超时建议：5 秒
      // 失败处理：连续失败 3 次，设备应记录本地日志并尝试重新注册
      virtual void Heartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest* request, ::terminal_agent::v1::HeartbeatResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Heartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest* request, ::terminal_agent::v1::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 状态上报
      // 设备上报完整运行状态快照，包含性能指标和当前配置
      //
      // 调用频率：每 5 分钟一次，或状态发生重大变化时立即调用
      // 重大变化：status 变更、配置修改、固件升级完成、重启完成
      // 超时建议：10 秒
      // 失败处理：记录本地日志，下次周期重试（不需要立即重试，数据有周期性补偿）
      virtual void ReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport* request, ::terminal_agent::v1::StatusReportResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport* request, ::terminal_agent::v1::StatusReportResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 事件上报
      // 设备端发生特定事件时实时上报（故障、交易失败、配置变更、重启等）
      //
      // 调用频率：事件驱动，不固定
      // 超时建议：10 秒
      // 失败处理：写入本地持久化队列，网络恢复后重试（事件数据不能丢）
      virtual void ReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport* request, ::terminal_agent::v1::EventReportResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport* request, ::terminal_agent::v1::EventReportResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 指令执行结果回报
      // 设备执行完服务端下发的指令后，通过此 RPC 回报执行结果
      //
      // 调用频率：指令执行完后调用
      // 超时建议：10 秒
      // 失败处理：写入本地持久化队列，网络恢复后重试
      // 注意：command_id 必须与收到的 Command.command_id 一致
      virtual void ReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult* request, ::terminal_agent::v1::CommandResultResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult* request, ::terminal_agent::v1::CommandResultResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::HeartbeatResponse>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::HeartbeatResponse>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::StatusReportResponse>* AsyncReportStatusRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::StatusReportResponse>* PrepareAsyncReportStatusRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::EventReportResponse>* AsyncReportEventRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::EventReportResponse>* PrepareAsyncReportEventRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::CommandResultResponse>* AsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::terminal_agent::v1::CommandResultResponse>* PrepareAsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::terminal_agent::v1::HeartbeatResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::HeartbeatResponse>> AsyncHeartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::HeartbeatResponse>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::HeartbeatResponse>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::HeartbeatResponse>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    ::grpc::Status ReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::terminal_agent::v1::StatusReportResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::StatusReportResponse>> AsyncReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::StatusReportResponse>>(AsyncReportStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::StatusReportResponse>> PrepareAsyncReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::StatusReportResponse>>(PrepareAsyncReportStatusRaw(context, request, cq));
    }
    ::grpc::Status ReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::terminal_agent::v1::EventReportResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::EventReportResponse>> AsyncReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::EventReportResponse>>(AsyncReportEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::EventReportResponse>> PrepareAsyncReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::EventReportResponse>>(PrepareAsyncReportEventRaw(context, request, cq));
    }
    ::grpc::Status ReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::terminal_agent::v1::CommandResultResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::CommandResultResponse>> AsyncReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::CommandResultResponse>>(AsyncReportCommandResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::CommandResultResponse>> PrepareAsyncReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::CommandResultResponse>>(PrepareAsyncReportCommandResultRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Heartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest* request, ::terminal_agent::v1::HeartbeatResponse* response, std::function<void(::grpc::Status)>) override;
      void Heartbeat(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest* request, ::terminal_agent::v1::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport* request, ::terminal_agent::v1::StatusReportResponse* response, std::function<void(::grpc::Status)>) override;
      void ReportStatus(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport* request, ::terminal_agent::v1::StatusReportResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport* request, ::terminal_agent::v1::EventReportResponse* response, std::function<void(::grpc::Status)>) override;
      void ReportEvent(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport* request, ::terminal_agent::v1::EventReportResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult* request, ::terminal_agent::v1::CommandResultResponse* response, std::function<void(::grpc::Status)>) override;
      void ReportCommandResult(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult* request, ::terminal_agent::v1::CommandResultResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::HeartbeatResponse>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::HeartbeatResponse>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::StatusReportResponse>* AsyncReportStatusRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::StatusReportResponse>* PrepareAsyncReportStatusRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::StatusReport& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::EventReportResponse>* AsyncReportEventRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::EventReportResponse>* PrepareAsyncReportEventRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::EventReport& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::CommandResultResponse>* AsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::terminal_agent::v1::CommandResultResponse>* PrepareAsyncReportCommandResultRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandResult& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Heartbeat_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportEvent_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportCommandResult_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 心跳
    // 设备定期（建议 30-60 秒）调用，告知服务端"我还活着"
    // 服务端更新 last_heartbeat，并通过响应告知是否有待执行指令
    //
    // 调用频率：每 30-60 秒一次
    // 超时建议：5 秒
    // 失败处理：连续失败 3 次，设备应记录本地日志并尝试重新注册
    virtual ::grpc::Status Heartbeat(::grpc::ServerContext* context, const ::terminal_agent::v1::HeartbeatRequest* request, ::terminal_agent::v1::HeartbeatResponse* response);
    // 状态上报
    // 设备上报完整运行状态快照，包含性能指标和当前配置
    //
    // 调用频率：每 5 分钟一次，或状态发生重大变化时立即调用
    // 重大变化：status 变更、配置修改、固件升级完成、重启完成
    // 超时建议：10 秒
    // 失败处理：记录本地日志，下次周期重试（不需要立即重试，数据有周期性补偿）
    virtual ::grpc::Status ReportStatus(::grpc::ServerContext* context, const ::terminal_agent::v1::StatusReport* request, ::terminal_agent::v1::StatusReportResponse* response);
    // 事件上报
    // 设备端发生特定事件时实时上报（故障、交易失败、配置变更、重启等）
    //
    // 调用频率：事件驱动，不固定
    // 超时建议：10 秒
    // 失败处理：写入本地持久化队列，网络恢复后重试（事件数据不能丢）
    virtual ::grpc::Status ReportEvent(::grpc::ServerContext* context, const ::terminal_agent::v1::EventReport* request, ::terminal_agent::v1::EventReportResponse* response);
    // 指令执行结果回报
    // 设备执行完服务端下发的指令后，通过此 RPC 回报执行结果
    //
    // 调用频率：指令执行完后调用
    // 超时建议：10 秒
    // 失败处理：写入本地持久化队列，网络恢复后重试
    // 注意：command_id 必须与收到的 Command.command_id 一致
    virtual ::grpc::Status ReportCommandResult(::grpc::ServerContext* context, const ::terminal_agent::v1::CommandResult* request, ::terminal_agent::v1::CommandResultResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Heartbeat() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::HeartbeatRequest* /*request*/, ::terminal_agent::v1::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::terminal_agent::v1::HeartbeatRequest* request, ::grpc::ServerAsyncResponseWriter< ::terminal_agent::v1::HeartbeatResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportStatus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ReportStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportStatus(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::StatusReport* /*request*/, ::terminal_agent::v1::StatusReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportStatus(::grpc::ServerContext* context, ::terminal_agent::v1::StatusReport* request, ::grpc::ServerAsyncResponseWriter< ::terminal_agent::v1::StatusReportResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportEvent() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ReportEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportEvent(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::EventReport* /*request*/, ::terminal_agent::v1::EventReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportEvent(::grpc::ServerContext* context, ::terminal_agent::v1::EventReport* request, ::grpc::ServerAsyncResponseWriter< ::terminal_agent::v1::EventReportResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandResult* /*request*/, ::terminal_agent::v1::CommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportCommandResult(::grpc::ServerContext* context, ::terminal_agent::v1::CommandResult* request, ::grpc::ServerAsyncResponseWriter< ::terminal_agent::v1::CommandResultResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Heartbeat<WithAsyncMethod_ReportStatus<WithAsyncMethod_ReportEvent<WithAsyncMethod_ReportCommandResult<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::terminal_agent::v1::HeartbeatRequest, ::terminal_agent::v1::HeartbeatResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::terminal_agent::v1::HeartbeatRequest* request, ::terminal_agent::v1::HeartbeatResponse* response) { return this->Heartbeat(context, request, response); }));}
    void SetMessageAllocatorFor_Heartbeat(
        ::grpc::MessageAllocator< ::terminal_agent::v1::HeartbeatRequest, ::terminal_agent::v1::HeartbeatResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::terminal_agent::v1::HeartbeatRequest, ::terminal_agent::v1::HeartbeatResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::HeartbeatRequest* /*request*/, ::terminal_agent::v1::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::terminal_agent::v1::HeartbeatRequest* /*request*/, ::terminal_agent::v1::HeartbeatResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReportStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportStatus() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::terminal_agent::v1::StatusReport, ::terminal_agent::v1::StatusReportResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::terminal_agent::v1::StatusReport* request, ::terminal_agent::v1::StatusReportResponse* response) { return this->ReportStatus(context, request, response); }));}
    void SetMessageAllocatorFor_ReportStatus(
        ::grpc::MessageAllocator< ::terminal_agent::v1::StatusReport, ::terminal_agent::v1::StatusReportResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::terminal_agent::v1::StatusReport, ::terminal_agent::v1::StatusReportResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportStatus(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::StatusReport* /*request*/, ::terminal_agent::v1::StatusReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::terminal_agent::v1::StatusReport* /*request*/, ::terminal_agent::v1::StatusReportResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReportEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportEvent() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::terminal_agent::v1::EventReport, ::terminal_agent::v1::EventReportResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::terminal_agent::v1::EventReport* request, ::terminal_agent::v1::EventReportResponse* response) { return this->ReportEvent(context, request, response); }));}
    void SetMessageAllocatorFor_ReportEvent(
        ::grpc::MessageAllocator< ::terminal_agent::v1::EventReport, ::terminal_agent::v1::EventReportResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::terminal_agent::v1::EventReport, ::terminal_agent::v1::EventReportResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportEvent(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::EventReport* /*request*/, ::terminal_agent::v1::EventReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::terminal_agent::v1::EventReport* /*request*/, ::terminal_agent::v1::EventReportResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::terminal_agent::v1::CommandResult, ::terminal_agent::v1::CommandResultResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::terminal_agent::v1::CommandResult* request, ::terminal_agent::v1::CommandResultResponse* response) { return this->ReportCommandResult(context, request, response); }));}
    void SetMessageAllocatorFor_ReportCommandResult(
        ::grpc::MessageAllocator< ::terminal_agent::v1::CommandResult, ::terminal_agent::v1::CommandResultResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::terminal_agent::v1::CommandResult, ::terminal_agent::v1::CommandResultResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandResult* /*request*/, ::terminal_agent::v1::CommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportCommandResult(
      ::grpc::CallbackServerContext* /*context*/, const ::terminal_agent::v1::CommandResult* /*request*/, ::terminal_agent::v1::CommandResultResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Heartbeat<WithCallbackMethod_ReportStatus<WithCallbackMethod_ReportEvent<WithCallbackMethod_ReportCommandResult<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Heartbeat() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::HeartbeatRequest* /*request*/, ::terminal_agent::v1::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportStatus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ReportStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportStatus(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::StatusReport* /*request*/, ::terminal_agent::v1::StatusReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportEvent() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ReportEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportEvent(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::EventReport* /*request*/, ::terminal_agent::v1::EventReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandResult* /*request*/, ::terminal_agent::v1::CommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::HeartbeatRequest* /*request*/, ::terminal_agent::v1::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportStatus() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ReportStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportStatus(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::StatusReport* /*request*/, ::terminal_agent::v1::StatusReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportEvent() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ReportEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportEvent(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::EventReport* /*request*/, ::terminal_agent::v1::EventReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportEvent(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandResult* /*request*/, ::terminal_agent::v1::CommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportCommandResult(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Heartbeat(context, request, response); }));
    }
    ~WithRawCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::HeartbeatRequest* /*request*/, ::terminal_agent::v1::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportStatus() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportStatus(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::StatusReport* /*request*/, ::terminal_agent::v1::StatusReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportEvent() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportEvent(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportEvent(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::EventReport* /*request*/, ::terminal_agent::v1::EventReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportCommandResult(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandResult* /*request*/, ::terminal_agent::v1::CommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportCommandResult(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Heartbeat() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::terminal_agent::v1::HeartbeatRequest, ::terminal_agent::v1::HeartbeatResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::terminal_agent::v1::HeartbeatRequest, ::terminal_agent::v1::HeartbeatResponse>* streamer) {
                       return this->StreamedHeartbeat(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::HeartbeatRequest* /*request*/, ::terminal_agent::v1::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHeartbeat(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::terminal_agent::v1::HeartbeatRequest,::terminal_agent::v1::HeartbeatResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportStatus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::terminal_agent::v1::StatusReport, ::terminal_agent::v1::StatusReportResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::terminal_agent::v1::StatusReport, ::terminal_agent::v1::StatusReportResponse>* streamer) {
                       return this->StreamedReportStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportStatus(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::StatusReport* /*request*/, ::terminal_agent::v1::StatusReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::terminal_agent::v1::StatusReport,::terminal_agent::v1::StatusReportResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportEvent() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::terminal_agent::v1::EventReport, ::terminal_agent::v1::EventReportResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::terminal_agent::v1::EventReport, ::terminal_agent::v1::EventReportResponse>* streamer) {
                       return this->StreamedReportEvent(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportEvent(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::EventReport* /*request*/, ::terminal_agent::v1::EventReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportEvent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::terminal_agent::v1::EventReport,::terminal_agent::v1::EventReportResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportCommandResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportCommandResult() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::terminal_agent::v1::CommandResult, ::terminal_agent::v1::CommandResultResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::terminal_agent::v1::CommandResult, ::terminal_agent::v1::CommandResultResponse>* streamer) {
                       return this->StreamedReportCommandResult(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportCommandResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportCommandResult(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandResult* /*request*/, ::terminal_agent::v1::CommandResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportCommandResult(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::terminal_agent::v1::CommandResult,::terminal_agent::v1::CommandResultResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Heartbeat<WithStreamedUnaryMethod_ReportStatus<WithStreamedUnaryMethod_ReportEvent<WithStreamedUnaryMethod_ReportCommandResult<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Heartbeat<WithStreamedUnaryMethod_ReportStatus<WithStreamedUnaryMethod_ReportEvent<WithStreamedUnaryMethod_ReportCommandResult<Service > > > > StreamedService;
};

// ─── CommandService ──────────────────────────────────────
// 服务端推送指令给设备的服务
//
// 设备启动后调用 CommandStream 建立长连接，服务端有指令时通过 stream 推送
// 设备端需要处理：
//   1. 连接断开后的自动重连（指数退避：1s → 2s → 4s → ... → 最大 60s）
//   2. 重连后自动接收断线期间积压的指令
//   3. 收到指令后通过 DeviceService.ReportCommandResult 回报结果
class CommandService final {
 public:
  static constexpr char const* service_full_name() {
    return "terminal_agent.v1.CommandService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 指令流（server streaming）
    // 设备调用后建立长连接，服务端有新指令时通过 stream 推送
    //
    // 连接生命周期：
    //   设备启动 → 连接 CommandStream → 等待指令 → 执行 → 继续等待
    //   连接断开 → 指数退避重连 → 重连成功 → 收到积压指令
    //
    // 心跳保活：
    //   gRPC 底层 HTTP/2 自带 keepalive
    //   建议设置 keepalive 参数：
    //     Time = 30s（无数据时多久发 ping）
    //     Timeout = 10s（ping 多久没响应认为断开）
    //
    // 指令顺序：
    //   服务端按 issued_at 时间顺序推送
    //   设备端收到后应立即执行，不要缓冲
    //
    // 超时建议：连接本身无超时（长连接），但设备端应设置单条指令接收超时（如 30s）
    std::unique_ptr< ::grpc::ClientReaderInterface< ::terminal_agent::v1::Command>> CommandStream(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::terminal_agent::v1::Command>>(CommandStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::terminal_agent::v1::Command>> AsyncCommandStream(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::terminal_agent::v1::Command>>(AsyncCommandStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::terminal_agent::v1::Command>> PrepareAsyncCommandStream(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::terminal_agent::v1::Command>>(PrepareAsyncCommandStreamRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 指令流（server streaming）
      // 设备调用后建立长连接，服务端有新指令时通过 stream 推送
      //
      // 连接生命周期：
      //   设备启动 → 连接 CommandStream → 等待指令 → 执行 → 继续等待
      //   连接断开 → 指数退避重连 → 重连成功 → 收到积压指令
      //
      // 心跳保活：
      //   gRPC 底层 HTTP/2 自带 keepalive
      //   建议设置 keepalive 参数：
      //     Time = 30s（无数据时多久发 ping）
      //     Timeout = 10s（ping 多久没响应认为断开）
      //
      // 指令顺序：
      //   服务端按 issued_at 时间顺序推送
      //   设备端收到后应立即执行，不要缓冲
      //
      // 超时建议：连接本身无超时（长连接），但设备端应设置单条指令接收超时（如 30s）
      virtual void CommandStream(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest* request, ::grpc::ClientReadReactor< ::terminal_agent::v1::Command>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::terminal_agent::v1::Command>* CommandStreamRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::terminal_agent::v1::Command>* AsyncCommandStreamRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::terminal_agent::v1::Command>* PrepareAsyncCommandStreamRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::terminal_agent::v1::Command>> CommandStream(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::terminal_agent::v1::Command>>(CommandStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::terminal_agent::v1::Command>> AsyncCommandStream(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::terminal_agent::v1::Command>>(AsyncCommandStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::terminal_agent::v1::Command>> PrepareAsyncCommandStream(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::terminal_agent::v1::Command>>(PrepareAsyncCommandStreamRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CommandStream(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest* request, ::grpc::ClientReadReactor< ::terminal_agent::v1::Command>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::terminal_agent::v1::Command>* CommandStreamRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::terminal_agent::v1::Command>* AsyncCommandStreamRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::terminal_agent::v1::Command>* PrepareAsyncCommandStreamRaw(::grpc::ClientContext* context, const ::terminal_agent::v1::CommandStreamRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CommandStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 指令流（server streaming）
    // 设备调用后建立长连接，服务端有新指令时通过 stream 推送
    //
    // 连接生命周期：
    //   设备启动 → 连接 CommandStream → 等待指令 → 执行 → 继续等待
    //   连接断开 → 指数退避重连 → 重连成功 → 收到积压指令
    //
    // 心跳保活：
    //   gRPC 底层 HTTP/2 自带 keepalive
    //   建议设置 keepalive 参数：
    //     Time = 30s（无数据时多久发 ping）
    //     Timeout = 10s（ping 多久没响应认为断开）
    //
    // 指令顺序：
    //   服务端按 issued_at 时间顺序推送
    //   设备端收到后应立即执行，不要缓冲
    //
    // 超时建议：连接本身无超时（长连接），但设备端应设置单条指令接收超时（如 30s）
    virtual ::grpc::Status CommandStream(::grpc::ServerContext* context, const ::terminal_agent::v1::CommandStreamRequest* request, ::grpc::ServerWriter< ::terminal_agent::v1::Command>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_CommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CommandStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CommandStream(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandStreamRequest* /*request*/, ::grpc::ServerWriter< ::terminal_agent::v1::Command>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCommandStream(::grpc::ServerContext* context, ::terminal_agent::v1::CommandStreamRequest* request, ::grpc::ServerAsyncWriter< ::terminal_agent::v1::Command>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CommandStream<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CommandStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::terminal_agent::v1::CommandStreamRequest, ::terminal_agent::v1::Command>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::terminal_agent::v1::CommandStreamRequest* request) { return this->CommandStream(context, request); }));
    }
    ~WithCallbackMethod_CommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CommandStream(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandStreamRequest* /*request*/, ::grpc::ServerWriter< ::terminal_agent::v1::Command>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::terminal_agent::v1::Command>* CommandStream(
      ::grpc::CallbackServerContext* /*context*/, const ::terminal_agent::v1::CommandStreamRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CommandStream<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CommandStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CommandStream(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandStreamRequest* /*request*/, ::grpc::ServerWriter< ::terminal_agent::v1::Command>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CommandStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CommandStream(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandStreamRequest* /*request*/, ::grpc::ServerWriter< ::terminal_agent::v1::Command>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCommandStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CommandStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->CommandStream(context, request); }));
    }
    ~WithRawCallbackMethod_CommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CommandStream(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandStreamRequest* /*request*/, ::grpc::ServerWriter< ::terminal_agent::v1::Command>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* CommandStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_CommandStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_CommandStream() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::terminal_agent::v1::CommandStreamRequest, ::terminal_agent::v1::Command>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::terminal_agent::v1::CommandStreamRequest, ::terminal_agent::v1::Command>* streamer) {
                       return this->StreamedCommandStream(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_CommandStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CommandStream(::grpc::ServerContext* /*context*/, const ::terminal_agent::v1::CommandStreamRequest* /*request*/, ::grpc::ServerWriter< ::terminal_agent::v1::Command>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedCommandStream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::terminal_agent::v1::CommandStreamRequest,::terminal_agent::v1::Command>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_CommandStream<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_CommandStream<Service > StreamedService;
};

}  // namespace v1
}  // namespace terminal_agent


#endif  // GRPC_terminal_5fagent_2fv1_2fservice_2eproto__INCLUDED
